name: tests

on:
  push:
     branches: [ dev ]
  pull_request:
  workflow_call:

jobs:
  build-and-test:
    name: tests
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v7

    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Restore
      run: dotnet restore

    - name: Test
      run: dotnet test --no-restore
